### ISSUE TITLE
 “Мой отчет о результатах комита”

### ISSUE THREAD

**Issue by UMSF-K13-1-Borodina** [UMSF-K13-1-Borodina/K13-1-Borodina-MainProject#1]
@smoktii-igov
![1](https://cloud.githubusercontent.com/assets/19636820/15635425/db3c41e4-25e6-11e6-8f1a-a9e08a016270.jpg)
![2](https://cloud.githubusercontent.com/assets/19636820/15635426/db456f4e-25e6-11e6-8453-1f5798b67a87.jpg)
![3](https://cloud.githubusercontent.com/assets/19636820/15635428/db46afbc-25e6-11e6-9f36-df7944f736ee.jpg)
![4](https://cloud.githubusercontent.com/assets/19636820/15635427/db46a33c-25e6-11e6-8b0e-207b90ceca5e.jpg)
![5](https://cloud.githubusercontent.com/assets/19636820/15635429/db46d08c-25e6-11e6-8d1c-dc007c15ee59.jpg)
![6](https://cloud.githubusercontent.com/assets/19636820/15635430/db485128-25e6-11e6-8307-093821fd353a.jpg)
![7](https://cloud.githubusercontent.com/assets/19636820/15635431/db5964f4-25e6-11e6-8d87-1d3f81b87f3e.jpg)

1- В папке "Новая папка" создан локальный репозиторий(есть папка .git. Создавался через гитБаш командой git init).
2- интерфейс программы GitGui с закомиченым текстовым файлом, который содержит ФИО.
3-Внесли изменения в файл, добавив номер группы. Теперь нужно закомитить изменения. Т.к. они еще не закомичены, то  в Unstaged Changes присутствует наш файл. 
4- Закомитили его.
5 - подключаем репозиторий гитхаба.
6 - Пушим( отправляем) наш измененный файл в репозиторий на гитхабе( для первого раза может понадобиться имя пользователя и пароль)
7 - В данном окне показывается процесс пуша. Выпадают сообщения об ошибках или успехе.

**Comment by smoktii-igov** [comment]
Не выставлены лэблы, не назначено задание на меня.

**Comment by UMSF-K13-1-Borodina** [comment]
Сделала. Ждала, пока вас можно будет добавить.

**Comment by smoktii-igov** [comment]
Ок
