### ISSUE TITLE
“Мой отчет о результатах комита 2”

### ISSUE THREAD

**Issue by UMSF-K13-1-Borodina** [UMSF-K13-1-Borodina/K13-1-Borodina-MainProject#2]
@smoktii-igov 

![1](https://cloud.githubusercontent.com/assets/19636820/15641473/e24aae40-2649-11e6-83ff-f0fd3e62fd4d.jpg)
![2](https://cloud.githubusercontent.com/assets/19636820/15641472/e24aade6-2649-11e6-85f2-75d4c788c527.jpg)
![3](https://cloud.githubusercontent.com/assets/19636820/15641474/e24b389c-2649-11e6-914b-ca7499291a66.jpg)
![4](https://cloud.githubusercontent.com/assets/19636820/15641476/e24b50ac-2649-11e6-8396-de19721f7109.jpg)
![5](https://cloud.githubusercontent.com/assets/19636820/15641475/e24b4ab2-2649-11e6-99b3-a29b45668f9d.jpg)
![6](https://cloud.githubusercontent.com/assets/19636820/15641477/e24bcd98-2649-11e6-8ba7-72038d1f047d.jpg)
![7](https://cloud.githubusercontent.com/assets/19636820/15641478/e26995b2-2649-11e6-9251-dbf74373093b.jpg)

1- В папке "Новая папка" создан локальный репозиторий(есть папка .git. Создавался через гитБаш командой git init).
2- интерфейс программы GitGui с закомиченым текстовым файлом, который содержит ФИО.
3-Внесли изменения в файл, добавив номер группы. Теперь нужно закомитить изменения. Т.к. они еще не закомичены, то в Unstaged Changes присутствует наш файл. 
4- Закомитили его.
5 - подключаем репозиторий гитхаба.
6 - Пушим( отправляем) наш измененный файл в репозиторий на гитхабе( для первого раза может понадобиться имя пользователя и пароль)
7 - В данном окне показывается процесс пуша. Выпадают сообщения об ошибках или успехе.

**Comment by Smoktii** [comment]
done
